### ISSUE TITLE
Determine how (or if) to support decoding the arbitrary protobuf encoded types stored in state

### ISSUE THREAD

**Issue by i-norden** [vulcanize/go-codec-dagcosmos#23]
Options:

1. Leave them undefined, e.g. for IAVL we've defined a multicodec packed content type for IAVL nodes and just leave the content type of the stored values unspecified. For ethereum's state trie, for example, there is a codec to specify trie nodes and there is also a codec to specify state account as the state value type. But for the storage trie there is only a codec for the trie node since the storage value types are indeterminate.
2. Define and register normal multicodec types for each protobuf type we wish to support.
3. Define a new composite multicodec, where the prefix byte specifies protobuf and suffix bytes specify specific protobuf types that have been registered.
4. Define a new multicodec that specifies that the first x bytes of the hash-linked object are another CID/multihash which references the .proto message definition that the remaining bytes should be unpacked into.
5. Define a new multicodec that specifies that the first x bytes of the hash-linked object *are* the .proto message definition that the remaining bytes should be unpacked into.

The problem with 1 is that it doesn't allow us to decode the types without a priori knowledge about them.

The problem with 2 is that we would have to define and register an indefinite, and surely immense, number of multicodec types.

The problem with 3 is that we are deviating from a true multicodec, there is no precedence for composite multicodecs, and we would still need to register an indefinite and immense number of these composite multicodecs (but we could perhaps maintain a separate registry for only the 2nd component of the composite multicodec and only the first component would need to be registered with the official registry).

The problem with 4 and 5 is that only the encoded protobuf types are stored in the leaf nodes of Comsos IAVL trees or hash-linked to from the leaf nodes of Cosmos SMTs. That is, the content stored in or hash-linked from the leaf nodes is only the binary encoded protobuf object and  it does not include the content prefixes required in 4 and 5. If we add these content prefixes (and include them as digest input) we no longer produce the expected content hash/IAVL/SMT.

**Comment by i-norden** [comment]
Actually this topic is made pretty much moot by the current SMT design. Since it doesn't store the values, or a hash reference of the values, but rather `hash(key, value)` as the leaf values in the SMT there is no way decoding this even as an IPLD link.

**Comment by i-norden** [comment]
For 4 and 5 we could define a "multicodec" procedure whereby the content prefixes introduced in these approaches is not included as digest input for the content hashes, this would almost certainly be too much of a deviation from proper IPLD to be accepted as canon.

**Comment by AFDudley** [comment]
>For 4 and 5 we could define a new "multicodec" procedure whereby the content prefixes introduced in these approaches is not included as part of the digest input for the content hashes

This seems like the best option from a cosmosSDK perspective, right? As an aside, we should not be trying to support IAVL in this solution.

**Comment by AFDudley** [comment]
Given the amount of automagic this unlocks for CosmosSDK blockchain devs, I think it being non-standard from an IPLD perspective is fine.

**Comment by i-norden** [comment]
@AFDudley That makes sense, and I agree. It is the most useful and elegant approach.  I think it's possible we can register a single multicodec for this experimental approach, or at lest reserve one, officially. We'd only need one in this approach so it seems less invasive then 2 or 3 which, while canonical multicodecs, would require registering tons of multicodecs.

I think 4 is the obvious choice out of these two, as 5 adds a bunch of additional, redundant, and variable length bytes to each of these IPLD blocks whereas 4 only adds a short fixed number of bytes. But, 4 does make the multicodec's decode procedure more complicated as we need to fetch another IPLD block to decode the IPLD block.

**Comment by AFDudley** [comment]
Fetching the second block will cost nothing practically, so 4 is the way to go.

**Comment by i-norden** [comment]
#4 approach is complicated by .protobuf definitions that depend on/import other .protobuf types

We could define a new .protobuf standard that uses CIDs for referencing and importing types

**Comment by i-norden** [comment]
Closing this since we have tentatively settled on our approach and an ADR PR has been opened against the SDK to formalize this approach.

This issue is now the issue to track: https://github.com/vulcanize/go-codec-dagcosmos/issues/43
